In [2]:
import numpy as np

In [4]:
benimDizim = np.arange(0,15)

In [5]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
benimDizim[5]

5

In [10]:
benimDizim[3:8] # 3'den 8'e kadar 8 dahil değil, getir

array([3, 4, 5, 6, 7])

In [13]:
benimDizim[3:8] = -5 # indexlerin değerini -5 yaptık

In [14]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [15]:
baskaDizi = np.arange(0,24)

In [16]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
slicingDizisi = baskaDizi[4:9]

In [24]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [25]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
type(slicingDizisi)

numpy.ndarray

In [29]:
slicingDizisi[:] = 700

In [30]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [32]:
baskaDizi # slicingle aldığımız değerlerde değişti

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [33]:
ornekDizi = np.arange(0,24)

In [34]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
ornekDiziKopyasi = ornekDizi.copy()

In [36]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[3:6]

In [39]:
ornekDiziKopyasiSlicing[:] = 800

In [40]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [41]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [42]:
ornekDizi # burda değişiklik olmadı copy() sayesinde

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [43]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [47]:
benimMatrixDizim = np.array(benimListem)

In [48]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [49]:
benimMatrixDizim[0]

array([10, 20, 30])

In [50]:
benimMatrixDizim[1][2]

40

In [51]:
benimMatrixDizim[1,2] # yukardakiyle aynı row =1, column=2

40

In [55]:
benimMatrixDizim[2:,2]

array([60])

In [58]:
benimMatrixDizim[2:,2:]

array([[60]])

In [64]:
yeniListe = [[0,1,2,3,4,],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [65]:
yeniMatrix = np.array(yeniListe)

In [66]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
yeniMatrix[[4,2,0]] # 0, 2 ve 4'üncü index'leri getirdi

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [72]:
yeniBirDizi = np.random.randint(1,100,20)

In [73]:
yeniBirDizi

array([67, 64, 25,  9, 87, 98, 28, 40, 58, 57, 73, 52, 90, 74, 40,  3, 25,
       59, 20, 51])

In [75]:
yeniBirDizi > 24  # 24'ten büyük değerleri boolean(True/False) olarak döndürüyor

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True])

In [77]:
yeniBirDizi

array([67, 64, 25,  9, 87, 98, 28, 40, 58, 57, 73, 52, 90, 74, 40,  3, 25,
       59, 20, 51])

In [78]:
sonucDizisi = yeniBirDizi > 24 

In [79]:
sonucDizisi # degisikligi bu diziye atadık ve gördük

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True])

In [80]:
yeniBirDizi # burda degisiklik olmadı

array([67, 64, 25,  9, 87, 98, 28, 40, 58, 57, 73, 52, 90, 74, 40,  3, 25,
       59, 20, 51])

In [81]:
yeniBirDizi[sonucDizisi] # sadece 24'ten büyük değerleri getirdi !!!! öenmli

array([67, 64, 25, 87, 98, 28, 40, 58, 57, 73, 52, 90, 74, 40, 25, 59, 51])

In [83]:
yeniBirDizi[yeniBirDizi > 24] # yukardakiyle aynı sonucu verir --> Filtreleme de denebilir buna

array([67, 64, 25, 87, 98, 28, 40, 58, 57, 73, 52, 90, 74, 40, 25, 59, 51])

In [84]:
sonDizi = np.arange(0,24)

In [85]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [86]:
sonDizi + sonDizi # toplama

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [87]:
sonDizi * sonDizi 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [88]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [89]:
sonDizi / sonDizi # 0'ı 0'a bölme de uyarı veriyor sadece

C:\Users\reco1\AppData\Local\Temp/ipykernel_10196/1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [92]:
np.sqrt(sonDizi) # karekökü alma

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [93]:
np.max(sonDizi)

23

In [94]:
np.min(sonDizi)

0